//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refhub.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Refhub.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email entered is already registered..
        /// </summary>
        internal static string Account_EmailAlready {
            get {
                return ResourceManager.GetString("Account_EmailAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        internal static string Account_Error_AddToRole {
            get {
                return ResourceManager.GetString("Account_Error_AddToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login attempt is invalid..
        /// </summary>
        internal static string Account_LoginInvalid {
            get {
                return ResourceManager.GetString("Account_LoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration encountered an error..
        /// </summary>
        internal static string Account_RegisterInvalid {
            get {
                return ResourceManager.GetString("Account_RegisterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one associated author is required..
        /// </summary>
        internal static string Book_AnotherIdMinLength {
            get {
                return ResourceManager.GetString("Book_AnotherIdMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a writer.
        /// </summary>
        internal static string Book_AnotherIdRequired {
            get {
                return ResourceManager.GetString("Book_AnotherIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a category.
        /// </summary>
        internal static string Book_CategoryIdRequired {
            get {
                return ResourceManager.GetString("Book_CategoryIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        internal static string Book_FileRequired {
            get {
                return ResourceManager.GetString("Book_FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Image.
        /// </summary>
        internal static string Book_ImageRequired {
            get {
                return ResourceManager.GetString("Book_ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of pages and select.
        /// </summary>
        internal static string Book_PageCountRequired {
            get {
                return ResourceManager.GetString("Book_PageCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title length in the browser should be a maximum of 450 characters..
        /// </summary>
        internal static string Book_SlugMaxLength {
            get {
                return ResourceManager.GetString("Book_SlugMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title in the browser..
        /// </summary>
        internal static string Book_SlugRequired {
            get {
                return ResourceManager.GetString("Book_SlugRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the book title.
        /// </summary>
        internal static string Book_TitleRequired {
            get {
                return ResourceManager.GetString("Book_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the description of category book .
        /// </summary>
        internal static string Category_Description {
            get {
                return ResourceManager.GetString("Category_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the category book title.
        /// </summary>
        internal static string Category_NameRequired {
            get {
                return ResourceManager.GetString("Category_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Invalid.
        /// </summary>
        internal static string ConfirmPassword_Compare_Invalid {
            get {
                return ResourceManager.GetString("ConfirmPassword_Compare_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Confirm Password!.
        /// </summary>
        internal static string ConfirmPassword_Required {
            get {
                return ResourceManager.GetString("ConfirmPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email is not Valid!.
        /// </summary>
        internal static string Email_Format_Invalid {
            get {
                return ResourceManager.GetString("Email_Format_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Email .
        /// </summary>
        internal static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author not found.
        /// </summary>
        internal static string Error_AuthorNotFound {
            get {
                return ResourceManager.GetString("Error_AuthorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncertain.
        /// </summary>
        internal static string Error_NotDefined {
            get {
                return ResourceManager.GetString("Error_NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug has already been used..
        /// </summary>
        internal static string Error_SlugExists {
            get {
                return ResourceManager.GetString("Error_SlugExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName is Required.
        /// </summary>
        internal static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword found.
        /// </summary>
        internal static string Keyword_AlreadyExists {
            get {
                return ResourceManager.GetString("Keyword_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword not found.
        /// </summary>
        internal static string Keyword_NotFound {
            get {
                return ResourceManager.GetString("Keyword_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose a keyword!.
        /// </summary>
        internal static string Keyword_Required {
            get {
                return ResourceManager.GetString("Keyword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be a maximum of 50 characters..
        /// </summary>
        internal static string Name_Max_50 {
            get {
                return ResourceManager.GetString("Name_Max_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain at least one letter, one number and 6 characters..
        /// </summary>
        internal static string Password_Regex_Invalid {
            get {
                return ResourceManager.GetString("Password_Regex_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter The Password!.
        /// </summary>
        internal static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me! .
        /// </summary>
        internal static string RememberMe_Display {
            get {
                return ResourceManager.GetString("RememberMe_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slug must be a maximum of 450 characters..
        /// </summary>
        internal static string Slug_Max_450 {
            get {
                return ResourceManager.GetString("Slug_Max_450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a slug name.
        /// </summary>
        internal static string Slug_NameRequired {
            get {
                return ResourceManager.GetString("Slug_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug  is Required.
        /// </summary>
        internal static string SlugRequired {
            get {
                return ResourceManager.GetString("SlugRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refhub.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not found.
        /// </summary>
        internal static string User_NotFound {
            get {
                return ResourceManager.GetString("User_NotFound", resourceCulture);
            }
        }
    }
}
