//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refhub.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Refhub.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email entered is already registered..
        /// </summary>
        public static string Account_EmailAleady {
            get {
                return ResourceManager.GetString("Account_EmailAleady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string Account_Error_AddToRole {
            get {
                return ResourceManager.GetString("Account_Error_AddToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login attempt is invalid..
        /// </summary>
        public static string Account_LoginInvalid {
            get {
                return ResourceManager.GetString("Account_LoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration encountered an error..
        /// </summary>
        public static string Account_RegisterInValid {
            get {
                return ResourceManager.GetString("Account_RegisterInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a writer.
        /// </summary>
        public static string Book_AnotherIdRequired {
            get {
                return ResourceManager.GetString("Book_AnotherIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a category.
        /// </summary>
        public static string Book_CategoryIdRequired {
            get {
                return ResourceManager.GetString("Book_CategoryIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        public static string Book_FileRequired {
            get {
                return ResourceManager.GetString("Book_FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Image.
        /// </summary>
        public static string Book_ImageRequired {
            get {
                return ResourceManager.GetString("Book_ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of pages and select.
        /// </summary>
        public static string Book_PageCountRequired {
            get {
                return ResourceManager.GetString("Book_PageCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title in the browser..
        /// </summary>
        public static string Book_SlugRequired {
            get {
                return ResourceManager.GetString("Book_SlugRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the category book title.
        /// </summary>
        public static string Book_Title_CategoryRequired {
            get {
                return ResourceManager.GetString("Book_Title_CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the book title.
        /// </summary>
        public static string Book_TitleRequired {
            get {
                return ResourceManager.GetString("Book_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the description of category book .
        /// </summary>
        public static string Category_Description {
            get {
                return ResourceManager.GetString("Category_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Invalid.
        /// </summary>
        public static string ConfirmPassword_Compare_Invalid {
            get {
                return ResourceManager.GetString("ConfirmPassword_Compare_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Confirm Password !.
        /// </summary>
        public static string ConfirmPassword_Required {
            get {
                return ResourceManager.GetString("ConfirmPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email is not Valid !.
        /// </summary>
        public static string Email_Format_Invalid {
            get {
                return ResourceManager.GetString("Email_Format_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Email .
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author not found.
        /// </summary>
        public static string Error_AuthorNotfound {
            get {
                return ResourceManager.GetString("Error_AuthorNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncertain.
        /// </summary>
        public static string Error_NotDefinde {
            get {
                return ResourceManager.GetString("Error_NotDefinde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug has already been used..
        /// </summary>
        public static string Error_SlugExists {
            get {
                return ResourceManager.GetString("Error_SlugExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName is Required.
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword notfound.
        /// </summary>
        public static string Keyword_Notfound {
            get {
                return ResourceManager.GetString("Keyword_Notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chooese a keyword !.
        /// </summary>
        public static string Keyword_Required {
            get {
                return ResourceManager.GetString("Keyword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choese a name of slug.
        /// </summary>
        public static string Name_Slug_Required {
            get {
                return ResourceManager.GetString("Name_Slug_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain at least one letter, one number and 6 characters..
        /// </summary>
        public static string Password_Regex_Invalid {
            get {
                return ResourceManager.GetString("Password_Regex_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter The Password !.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me ! .
        /// </summary>
        public static string RememberMe_Display {
            get {
                return ResourceManager.GetString("RememberMe_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug  is Required.
        /// </summary>
        public static string SlugRequired {
            get {
                return ResourceManager.GetString("SlugRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refhub.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not found.
        /// </summary>
        public static string User_NotFound {
            get {
                return ResourceManager.GetString("User_NotFound", resourceCulture);
            }
        }
    }
}
